//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VET
{
    using System;
    using System.Collections.Generic;
    
    public partial class hayvanlar
    {
        public string ID { get; set; }
        public string Tür { get; set; }
        public string Cins { get; set; }
        public string Hastalık { get; set; }
        public string Parazit { get; set; }
        public string Karma1 { get; set; }
        public string Karma2 { get; set; }
        public string Kuduz { get; set; }
        public string Lösemi { get; set; }
        public string Mantar { get; set; }
    
        public virtual kisiler kisiler { get; set; }
    }
}
