//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VET
{
    using System;
    using System.Collections.Generic;
    
    public partial class kisiler
    {
        public string TC { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Mail { get; set; }
        public string Telefon { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public int Ücret { get; set; }
    
        public virtual hayvanlar hayvanlar { get; set; }
    }
}
